export const ModalContent = {
  email: "Email",
  password: "Password",
  emailPlaceholder: "example@gmail.com",
  passwordPlaceholder: "password",
  emailError: "Invalid email input",
  passwordError: "Invalid password input",
  FIREBASE_ERRORS: [
    {
      code: "auth/user-not-found",
      message: "No matching account found",
    },
    {
      code: "auth/email-already-in-use",
      message: "Email is already in use",
    },
    {
      code: "auth/weak-password",
      message: "Weak Password! (Password must be at least 6 characters)",
    },
    {
      code: "auth/wrong-password",
      message: "Wrong password!",
    },
    {
      code: "auth/too-many-requests",
      message:
        "Access to this account has been temporarily disabled due to many failed login attempts! Please try again later!",
    },
  ],
  signIn: {
    title: "Sign in to your account",
    emailInputVisible: true,
    passInputVisible: true,
    button: "Sign In",
    buttonVisible: true,
    msg1: "Don't have an account? ",
    link1: "Sign up",
    link2: "Forgot password?",
  },
  signUp: {
    title: "Sign up an account",
    emailInputVisible: true,
    passInputVisible: true,
    button: "Create account",
    buttonVisible: true,
    msg1: "Already have an account? ",
    link1: "Sign in",
    link2: "",
  },
  updatePassword: {
    title: "Update your password",
    intro: "Enter your email link, we will send you the recovery link",
    emailInputVisible: true,
    passInputVisible: false,
    button: "Update password",
    buttonVisible: true,
    msg1: "",
    link1: "",
    link2: "",
  },
  updatePasswordSent: {
    title: "",
    intro:
      "We have sent the update password link to your email, please check that ！",
    emailInputVisible: false,
    passInputVisible: false,
    buttonVisible: false,
    button: "",
    msg1: "",
    link1: "",
    link2: "",
  },
  createProductSuccess: {
    title: "",
    intro: "Created product successfully！",
    emailInputVisible: false,
    passInputVisible: false,
    buttonVisible: false,
    button: "",
    msg1: "",
    link1: "",
    link2: "",
  },
};
